source ~/.terminal-config/git-prompt.sh
source ~/.terminal-config/git-completion.bash

# Define some colors for the terminal to use
blue="\[\033[0;34m\]"
gray="\[\033[38;5;246m\]"
pink="\[\033[38;5;211m\]"
green="\[\033[38;5;40m\]"
reset="\[\033[0m\]"

export GIT_PS1_SHOWDIRTYSTATE=1

export PS1="$blue\u$green@\h$pink\$(__git_ps1)$gray \W
$ $reset"
